api_login:
  path: /api/login

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

api_clothes_create:
    path: /api/clothes
    controller: App\Controller\ClothesController::create
    methods: POST

forgot_password:
    path: /api/forgot-password
    controller: App\Controller\AuthController::forgotPassword
    methods: POST
